"""empty message

Revision ID: 240fd7c677a0
Revises: 610c370e8abb
Create Date: 2020-06-03 19:55:08.132864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240fd7c677a0'
down_revision = '610c370e8abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('body', sa.String(length=7500), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_date_created'), 'journals', ['date_created'], unique=False)
    op.create_index(op.f('ix_journals_title'), 'journals', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journals_title'), table_name='journals')
    op.drop_index(op.f('ix_journals_date_created'), table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###
