"""empty message

Revision ID: 33d38df42b84
Revises: 4ce7c0bc6275
Create Date: 2020-05-05 22:39:51.278448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d38df42b84'
down_revision = '4ce7c0bc6275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_email'), 'contributors', ['email'], unique=True)
    op.create_index(op.f('ix_contributors_first_name'), 'contributors', ['first_name'], unique=False)
    op.create_index(op.f('ix_contributors_last_name'), 'contributors', ['last_name'], unique=False)
    op.create_index(op.f('ix_contributors_username'), 'contributors', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributors_username'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_last_name'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_first_name'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_email'), table_name='contributors')
    op.drop_table('contributors')
    # ### end Alembic commands ###
