language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

install:
 - sudo apt install python3-pip
 - pip3 install flask

script:
  - python3 flask-backend/test.py

