language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
install: 
  - pip install flask
  - pip install Flask-SQLAlchemy
  - pip install Flask-Migrate
  - pip install flask-cors
  - pip install flask-login
script: python flask-backend/test.py