language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# unit tests have dependency on flask
install: 
  - pip install flask
script: python flask-backend/test.py
  