
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
install:
-pip3  install flask

script:
  - cd flask-backend
  - python3 test.py

